
development:
  cloud_name: jsam
  api_key: '395612515316282'
  api_secret: bh0NjwHeeahHCIWQPIzlqePgQf4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: jsam
  api_key: '395612515316282'
  api_secret: bh0NjwHeeahHCIWQPIzlqePgQf4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: jsam
  api_key: '395612515316282'
  api_secret: bh0NjwHeeahHCIWQPIzlqePgQf4
  enhance_image_tag: true
  static_image_support: false